/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mypackage;

/**
 *
 * @author drago
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }
    public String user;
    public String pass;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        UserField = new javax.swing.JFormattedTextField();
        PassField = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        AddBussinessbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        SignUpButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SignInButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 51));
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel3.setText("!Log in screen!");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 300, 130, 40);

        UserField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserFieldActionPerformed(evt);
            }
        });
        getContentPane().add(UserField);
        UserField.setBounds(310, 192, 120, 30);

        PassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassFieldActionPerformed(evt);
            }
        });
        getContentPane().add(PassField);
        PassField.setBounds(310, 230, 120, 30);

        jLabel4.setText("Username/ Email :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 200, 110, 16);

        jLabel5.setText("Password :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(240, 230, 60, 16);

        AddBussinessbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AddBussinessbtn.setText("Add Business");
        AddBussinessbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBussinessbtnActionPerformed(evt);
            }
        });
        getContentPane().add(AddBussinessbtn);
        AddBussinessbtn.setBounds(540, 430, 200, 40);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Or if you dont have an account : ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(210, 330, 270, 25);

        SignUpButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SignUpButton.setText("Sign up");
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SignUpButton);
        SignUpButton.setBounds(490, 330, 110, 32);

        jLabel7.setText("!For testing purposes Username/pass = \" test\"!");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(440, 200, 260, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FounItfullLogo(1).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 30, 400, 145);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("If you have a business you can provide it as a drop-off point");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 440, 510, 25);

        SignInButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SignInButton1.setText("Log in");
        SignInButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(SignInButton1);
        SignInButton1.setBounds(310, 270, 110, 40);

        jLabel8.setBackground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 200, 550, 230);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserFieldActionPerformed
        // TODO add your handling code here:
        user=UserField.getText();
    }//GEN-LAST:event_UserFieldActionPerformed

    private void PassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassFieldActionPerformed
        // TODO add your handling code here:
        pass=String.valueOf(PassField.getPassword());
    }//GEN-LAST:event_PassFieldActionPerformed

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
        // TODO add your handling code here:
        new Signupscrn().setVisible(true);
    }//GEN-LAST:event_SignUpButtonActionPerformed

    private void AddBussinessbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBussinessbtnActionPerformed
        // TODO add your handling code here:
         new Signbus().setVisible(true);       
    }//GEN-LAST:event_AddBussinessbtnActionPerformed

    private void SignInButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInButton1ActionPerformed
        // TODO add your handling code here:System.out.println(pass);
                System.out.println(user);

        if ("test".equals(pass) && "test".equals(user)){
            new JFrame().setVisible(true);
    }
    }//GEN-LAST:event_SignInButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBussinessbtn;
    private javax.swing.JPasswordField PassField;
    private javax.swing.JButton SignInButton1;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JFormattedTextField UserField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
